import Foundation

// MARK: - Clipboard history

public struct ClipboardEntry: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var text: String
    public var date: Date
    public var sourceBundleID: String?
    public var pinned: Bool

    public init(id: String = UUID().uuidString, text: String, date: Date, sourceBundleID: String? = nil, pinned: Bool = false) {
        self.id = id; self.text = text; self.date = date; self.sourceBundleID = sourceBundleID; self.pinned = pinned
    }
}

/// Text clipboard history that respects the nspasteboard.org privacy conventions, so
/// passwords copied from password managers are never recorded.
public struct ClipboardHistory: Codable, Equatable, Sendable {
    public private(set) var entries: [ClipboardEntry] = []
    /// Lowering it drops the oldest unpinned entries straight away, not at the next copy.
    public var limit: Int {
        didSet {
            if limit < 1 { limit = 1 }
            trim()
        }
    }
    /// Apps the user chose to ignore (Settings → Shelf & Clipboard). Adding one also forgets
    /// what was already kept from it, pinned or not.
    public var ignoredApps: Set<String> = [] {
        didSet { entries.removeAll { $0.sourceBundleID.map(ignoredApps.contains) ?? false } }
    }
    /// Skip what looks like a password copied in a browser, where password manager extensions
    /// copy as the browser itself: text shaped like a generated password from a web page
    /// (`looksLikeGeneratedPassword`), anything shaped like a password from an extension's own
    /// page (`looksLikePassword`).
    public var skipsSecrets = true

    enum CodingKeys: String, CodingKey { case entries, limit }

    /// Pasteboard types that mark content as secret or throwaway (nspasteboard.org).
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    /// Apps whose copies are never recorded, regardless of types.
    /// Bundle identifiers of password managers (identifiers, not credentials).
    public static let ignoredApps: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.apple.Passwords.MenuBarExtra",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
    ]

    /// Browsers, whose password manager extensions copy passwords as the browser.
    public static var browsers: Set<String> { Browsers.bundleIDs }

    /// The pasteboard type where Chrome, Edge, Brave, Arc and other Chromium browsers put the
    /// address of the page or extension a copy came from. Islet reads it to decide, never keeps it.
    public static let sourceURLType = "org.chromium.source-url"

    /// Chrome Web Store ids of password manager extensions (identifiers, not credentials). A
    /// copy from one of their pages is never kept, like a copy from their apps.
    public static let passwordManagerExtensions: Set<String> = [
        "aeblfdkhhhdcdjpifhhbdiojplfjncoa", // 1Password
        "nngceckbapebfimnlniiiahkandclblb", // Bitwarden
        "hdokiejnpimakedhajhdlcegeplioahd", // LastPass
        "fdjamakpfbbddfjaooikfcpapjohcfmg", // Dashlane
        "pejdijmoenmkgeppbflobdenhhabjlaj", // iCloud Passwords
        "ghmbeldphafepmbegfdlkpapadhbakde", // Proton Pass
        "bfogiafebfohielmmehodmfbbebbbpei", // Keeper
        "oboonakemofpalcgghocfoadofidjkkk", // KeePassXC-Browser
        "fooolghllnmhmmndgjiamiiodkpenpbb", // NordPass
        "pnlccmojcmeohlpggmfnbbiapkmbliob", // RoboForm
    ]

    public static let maxTextLength = 100_000
    /// The most text kept in all (bytes of UTF-8), whatever the count: 500 long copies would
    /// otherwise hold 50 MB. The oldest unpinned entries go first.
    public static let maxTotalBytes = 4_000_000

    public init(limit: Int = 30) { self.limit = max(1, limit) }

    public enum Outcome: Equatable, Sendable { case added, moved, ignored }

    /// - Parameter sourceURL: the page or extension a browser says the copy came from
    ///   (`sourceURLType`), used for the decision only.
    @discardableResult
    public mutating func add(_ text: String, types: [String], sourceBundleID: String?, sourceURL: String? = nil,
                             now: Date) -> Outcome {
        guard shouldKeep(text, types: types, sourceBundleID: sourceBundleID, sourceURL: sourceURL) else { return .ignored }
        if let i = entries.firstIndex(where: { $0.text == text }) {
            var e = entries.remove(at: i)
            e.date = now
            e.sourceBundleID = sourceBundleID ?? e.sourceBundleID
            entries.insert(e, at: 0)
            return .moved
        }
        entries.insert(ClipboardEntry(text: text, date: now, sourceBundleID: sourceBundleID), at: 0)
        trim()
        return .added
    }

    public mutating func togglePin(id: String) {
        guard let i = entries.firstIndex(where: { $0.id == id }) else { return }
        entries[i].pinned.toggle()
    }

    /// Whether a copy is kept: never secret or throwaway types (nspasteboard.org), password
    /// managers' apps and extensions, apps the user ignored, likely passwords from a browser,
    /// blank text or text over `maxTextLength`.
    public func shouldKeep(_ text: String, types: [String], sourceBundleID: String?, sourceURL: String? = nil) -> Bool {
        if types.contains(where: Self.ignoredTypes.contains) { return false }
        if let b = sourceBundleID, Self.ignoredApps.contains(b) || ignoredApps.contains(b) { return false }
        if let id = sourceURL.flatMap(Self.extensionID), Self.passwordManagerExtensions.contains(id) { return false }
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, text.count <= Self.maxTextLength else { return false }
        if skipsSecrets, let b = sourceBundleID, Browsers.browser(for: b) != nil {
            // An extension's own page copies little but what it holds; a web page copies all sorts.
            let fromExtension = sourceURL.map(Self.isExtensionPage) ?? false
            if fromExtension ? Self.looksLikePassword(text) : Self.looksLikeGeneratedPassword(text) { return false }
        }
        return true
    }

    // MARK: What a password looks like

    /// The extension a browser's source address names (`chrome-extension://<id>/…`), if any.
    static func extensionID(_ sourceURL: String) -> String? {
        let prefix = "chrome-extension://"
        guard sourceURL.lowercased().hasPrefix(prefix) else { return nil }
        let id = sourceURL.dropFirst(prefix.count).prefix { $0 != "/" && $0 != "?" && $0 != "#" }
        return id.isEmpty ? nil : id.lowercased()
    }

    /// Whether a browser's source address is one of its extensions' own pages.
    static func isExtensionPage(_ sourceURL: String) -> Bool {
        let s = sourceURL.lowercased()
        return ["chrome-extension://", "moz-extension://", "safari-web-extension://", "extension://"].contains { s.hasPrefix($0) }
    }

    /// Safari's (and the Passwords app's) strong password: three groups of six letters and
    /// digits joined by hyphens, with a capital and a digit ("fujvy7-Bezkah-doqnij").
    static func isSafariStrongPassword(_ text: String) -> Bool {
        let groups = text.split(separator: "-", omittingEmptySubsequences: false)
        guard groups.count == 3,
              groups.allSatisfy({ $0.count == 6 && $0.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber) } }) else { return false }
        return text.contains(where: \.isUppercase) && text.contains(where: \.isLowercase) && text.contains(where: \.isNumber)
    }

    /// How a generated password looks, which text copied from a web page almost never does:
    /// Safari's strong passwords, or plain ASCII mixing both cases with digits or symbols where
    /// the letters don't make words. "xT3!kP9#qr" falls apart into x, T, k, P and qr, while
    /// "Windows11", "COVID-19", "iPhone15Pro", "Report_Q3-2026.pdf" and UUIDs keep their words
    /// (or use one case) and are kept. Some generated passwords read wordy enough to be kept:
    /// the rule would rather keep a password on this Mac than lose ordinary text.
    public static func looksLikeGeneratedPassword(_ text: String) -> Bool {
        guard looksLikePassword(text), text.unicodeScalars.allSatisfy({ $0.value > 32 && $0.value < 127 }) else { return false }
        if isSafariStrongPassword(text) { return true }
        let letters = text.filter(\.isLetter)
        guard letters.contains(where: \.isLowercase), letters.contains(where: \.isUppercase) else { return false }
        // Hexadecimal: hashes, colours, UUIDs.
        if letters.allSatisfy({ "abcdefABCDEF".contains($0) }) { return false }
        let all = words(in: text)
        let scraps = all.filter(isScrap).count
        return scraps >= 3 && scraps * 2 >= all.count
    }

    /// Units written in mixed case, each a word of its own ("3.2GHz", "5000mAh").
    static let units: Set<String> = [
        "Hz", "kHz", "MHz", "GHz", "THz", "Wh", "kWh", "MWh", "Ah", "mAh", "dB", "dBm", "kB", "KiB", "MiB", "GiB", "TiB",
        "kbps", "Mbps", "Gbps", "MBps", "GBps", "mL", "mW", "kW", "MW",
    ]

    /// The words in a text's letters, split the way names and code are written: "getHUDValue"
    /// is get, HUD and Value; "iOS" is i and OS. Digits and symbols separate words.
    static func words(in text: String) -> [String] {
        var out: [String] = []
        for run in text.split(whereSeparator: { !($0.isASCII && $0.isLetter) }) {
            if units.contains(String(run)) {
                out.append(String(run))
                continue
            }
            let c = Array(run)
            var i = 0
            while i < c.count {
                var j = i
                if c[i].isUppercase {
                    while j < c.count, c[j].isUppercase { j += 1 }
                    if j - i == 1 {
                        // A capital and the lower case after it: a capitalised word.
                        while j < c.count, c[j].isLowercase { j += 1 }
                    } else if j < c.count {
                        // Capitals, then lower case ("HTTPServer"): the last capital starts the next word.
                        j -= 1
                    }
                } else {
                    while j < c.count, c[j].isLowercase { j += 1 }
                }
                out.append(String(c[i..<j]))
                i = j
            }
        }
        return out
    }

    /// A scrap rather than a word: a lone letter, or letters without a vowel that aren't all
    /// capitals ("Hv", "qr", "Bzk"). Capitals alone ("HUD", "OS") read as an abbreviation.
    static func isScrap(_ word: String) -> Bool {
        if word.count == 1 { return true }
        if units.contains(word) || word.allSatisfy(\.isUppercase) { return false }
        return !word.contains { "aeiouyAEIOUY".contains($0) }
    }

    /// One line with no spaces, 8 to 128 characters, mixing at least three of lower case,
    /// upper case, digits and symbols. Links, paths, email addresses and domain names don't
    /// count, however mixed. Broad on purpose: only a copy from a browser extension's own page
    /// is held to it.
    public static func looksLikePassword(_ text: String) -> Bool {
        guard (8...128).contains(text.count), !text.contains(where: { $0.isWhitespace }) else { return false }
        if text.contains("://") || text.hasPrefix("www.") || text.hasPrefix("/") || text.hasPrefix("~/") { return false }
        if text.range(of: #"^[^@]+@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*\.[a-z]{2,24}$"#, options: .regularExpression) != nil { return false }
        if text.range(of: #"^([A-Za-z0-9-]+\.)+[a-z]{2,24}(/\S*)?$"#, options: .regularExpression) != nil { return false }
        var lower = false, upper = false, digit = false, symbol = false
        for c in text.unicodeScalars {
            switch c.properties.generalCategory {
            case .lowercaseLetter: lower = true
            case .uppercaseLetter: upper = true
            case .decimalNumber: digit = true
            default: symbol = true
            }
        }
        return [lower, upper, digit, symbol].filter { $0 }.count >= 3
    }

    public mutating func remove(id: String) { entries.removeAll { $0.id == id } }

    /// Clears everything except pinned entries ("Clear unpinned").
    public mutating func clear() { entries.removeAll { !$0.pinned } }

    /// Forgets everything, pinned entries too: clipboard history was switched off.
    public mutating func removeAll() { entries.removeAll() }

    public var hasUnpinned: Bool { entries.contains { !$0.pinned } }

    mutating func trim() {
        while entries.count > limit, let i = entries.lastIndex(where: { !$0.pinned }) {
            entries.remove(at: i)
        }
        var total = entries.reduce(0) { $0 + $1.text.utf8.count }
        while total > Self.maxTotalBytes, let i = entries.lastIndex(where: { !$0.pinned }) {
            total -= entries[i].text.utf8.count
            entries.remove(at: i)
        }
    }
}

// MARK: - File shelf

public struct ShelfItem: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var path: String
    public var addedAt: Date
    /// Security-scoped / regular bookmark so items survive renames and moves.
    public var bookmark: Data?

    public init(id: String = UUID().uuidString, path: String, addedAt: Date, bookmark: Data? = nil) {
        self.id = id; self.path = path; self.addedAt = addedAt; self.bookmark = bookmark
    }

    public var name: String { (path as NSString).lastPathComponent }
    public var fileExtension: String { (path as NSString).pathExtension.lowercased() }
}

/// Temporary holding area for files dragged onto the island.
public struct Shelf: Codable, Equatable, Sendable {
    public private(set) var items: [ShelfItem] = []
    public var limit: Int

    public init(limit: Int = 40) { self.limit = max(1, limit) }

    /// Add paths (deduplicated, newest first). Returns the paths that were new.
    @discardableResult
    public mutating func add(paths: [String], now: Date, bookmark: (String) -> Data? = { _ in nil }) -> [String] {
        var added: [String] = []
        for p in paths.reversed() where !p.isEmpty {
            let std = (p as NSString).standardizingPath
            if let i = items.firstIndex(where: { $0.path == std }) {
                let existing = items.remove(at: i)
                items.insert(existing, at: 0)
                continue
            }
            items.insert(ShelfItem(path: std, addedAt: now, bookmark: bookmark(std)), at: 0)
            added.append(std)
        }
        if items.count > limit { items.removeLast(items.count - limit) }
        return added.reversed()
    }

    public mutating func remove(id: String) { items.removeAll { $0.id == id } }
    public mutating func removeAll() { items.removeAll() }

    /// Drop entries whose file no longer exists. Files on a disk or share that isn't mounted
    /// right now stay (`isAvailable` dims them) until it comes back.
    public mutating func prune(exists: (String) -> Bool) {
        items.removeAll { item in
            guard !exists(item.path) else { return false }
            if let volume = Self.volume(of: item.path), !exists(volume) { return false }
            return true
        }
    }

    /// The external volume a path is on ("/Volumes/Backup"), or nil for the startup disk.
    public static func volume(of path: String) -> String? {
        let parts = (path as NSString).standardizingPath.split(separator: "/", omittingEmptySubsequences: true)
        guard parts.count >= 3, parts[0] == "Volumes" else { return nil }
        return "/Volumes/" + parts[1]
    }

    /// Whether an item can be opened now: false while the volume it is on isn't mounted.
    public static func isAvailable(_ item: ShelfItem, exists: (String) -> Bool) -> Bool {
        guard let volume = volume(of: item.path) else { return true }
        return exists(volume)
    }

    public mutating func updatePath(id: String, to path: String) {
        guard let i = items.firstIndex(where: { $0.id == id }) else { return }
        items[i].path = path
    }

    /// The bookmark for an item, made after it was added (away from the main thread).
    public mutating func setBookmark(_ data: Data?, forPath path: String) {
        guard let i = items.firstIndex(where: { $0.path == path }) else { return }
        items[i].bookmark = data
    }

    /// Items on the startup disk are quick to check, so they are checked at once. Ones on
    /// another volume (an external disk, or a network share that may not answer) are checked
    /// away from the main thread (`ShelfCheck`).
    public static func isOnStartupDisk(_ item: ShelfItem) -> Bool { volume(of: item.path) == nil }
}

/// What a look at a shelf file on another volume found.
public enum ShelfCheck: Equatable, Sendable {
    /// The file is there.
    case present
    /// Its volume is there and the file isn't: it leaves the shelf.
    case gone
    /// Its volume isn't mounted (or didn't answer in time): it stays, dimmed, until it is back.
    case unreachable

    public static func check(path: String, exists: (String) -> Bool) -> ShelfCheck {
        if exists(path) { return .present }
        if let volume = Shelf.volume(of: path), !exists(volume) { return .unreachable }
        return .gone
    }
}

// MARK: - System stats

public struct CPUTicks: Equatable, Sendable {
    public var user: UInt64, system: UInt64, idle: UInt64, nice: UInt64
    public init(user: UInt64, system: UInt64, idle: UInt64, nice: UInt64) {
        self.user = user; self.system = system; self.idle = idle; self.nice = nice
    }
}

public struct SystemStats: Equatable, Sendable {
    /// 0...1
    public var cpu: Double
    public var memoryUsed: UInt64
    public var memoryTotal: UInt64

    public init(cpu: Double, memoryUsed: UInt64, memoryTotal: UInt64) {
        self.cpu = cpu; self.memoryUsed = memoryUsed; self.memoryTotal = memoryTotal
    }

    public var memoryFraction: Double { memoryTotal == 0 ? 0 : Double(memoryUsed) / Double(memoryTotal) }

    /// CPU usage between two samples summed over all cores.
    public static func cpuUsage(previous: [CPUTicks], current: [CPUTicks]) -> Double {
        guard previous.count == current.count, !current.isEmpty else { return 0 }
        var busy: UInt64 = 0, total: UInt64 = 0
        for (a, b) in zip(previous, current) {
            let du = b.user &- a.user, ds = b.system &- a.system, dn = b.nice &- a.nice, di = b.idle &- a.idle
            // Counter wrap or reset: skip this core.
            guard b.user >= a.user, b.system >= a.system, b.idle >= a.idle, b.nice >= a.nice else { continue }
            busy += du + ds + dn
            total += du + ds + dn + di
        }
        return total == 0 ? 0 : Double(busy) / Double(total)
    }
}
