import Foundation

// MARK: - Clipboard history

public struct ClipboardEntry: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var text: String
    public var date: Date
    public var sourceBundleID: String?
    public var pinned: Bool

    public init(id: String = UUID().uuidString, text: String, date: Date, sourceBundleID: String? = nil, pinned: Bool = false) {
        self.id = id; self.text = text; self.date = date; self.sourceBundleID = sourceBundleID; self.pinned = pinned
    }
}

/// Text clipboard history that respects the nspasteboard.org privacy conventions, so
/// passwords copied from password managers are never recorded.
public struct ClipboardHistory: Codable, Equatable, Sendable {
    public private(set) var entries: [ClipboardEntry] = []
    public var limit: Int

    /// Pasteboard types that mark content as secret or throwaway (nspasteboard.org).
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    /// Apps whose copies are never recorded, regardless of types.
    /// Bundle identifiers of password managers (identifiers, not credentials).
    public static let ignoredApps: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.apple.Passwords.MenuBarExtra",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
    ]

    public static let maxTextLength = 100_000

    public init(limit: Int = 30) { self.limit = max(1, limit) }

    public enum Outcome: Equatable, Sendable { case added, moved, ignored }

    @discardableResult
    public mutating func add(_ text: String, types: [String], sourceBundleID: String?, now: Date, extraIgnoredApps: Set<String> = []) -> Outcome {
        if types.contains(where: Self.ignoredTypes.contains) { return .ignored }
        if let b = sourceBundleID, Self.ignoredApps.contains(b) || extraIgnoredApps.contains(b) { return .ignored }
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, text.count <= Self.maxTextLength else { return .ignored }
        if let i = entries.firstIndex(where: { $0.text == text }) {
            var e = entries.remove(at: i)
            e.date = now
            e.sourceBundleID = sourceBundleID ?? e.sourceBundleID
            entries.insert(e, at: 0)
            return .moved
        }
        entries.insert(ClipboardEntry(text: text, date: now, sourceBundleID: sourceBundleID), at: 0)
        trim()
        return .added
    }

    public mutating func togglePin(id: String) {
        guard let i = entries.firstIndex(where: { $0.id == id }) else { return }
        entries[i].pinned.toggle()
    }

    public mutating func remove(id: String) { entries.removeAll { $0.id == id } }

    /// Clears everything except pinned entries.
    public mutating func clear() { entries.removeAll { !$0.pinned } }

    mutating func trim() {
        while entries.count > limit, let i = entries.lastIndex(where: { !$0.pinned }) {
            entries.remove(at: i)
        }
    }
}

// MARK: - File shelf

public struct ShelfItem: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var path: String
    public var addedAt: Date
    /// Security-scoped / regular bookmark so items survive renames and moves.
    public var bookmark: Data?

    public init(id: String = UUID().uuidString, path: String, addedAt: Date, bookmark: Data? = nil) {
        self.id = id; self.path = path; self.addedAt = addedAt; self.bookmark = bookmark
    }

    public var name: String { (path as NSString).lastPathComponent }
    public var fileExtension: String { (path as NSString).pathExtension.lowercased() }
}

/// Temporary holding area for files dragged onto the island.
public struct Shelf: Codable, Equatable, Sendable {
    public private(set) var items: [ShelfItem] = []
    public var limit: Int

    public init(limit: Int = 40) { self.limit = max(1, limit) }

    /// Add paths (deduplicated, newest first). Returns the paths that were new.
    @discardableResult
    public mutating func add(paths: [String], now: Date, bookmark: (String) -> Data? = { _ in nil }) -> [String] {
        var added: [String] = []
        for p in paths.reversed() where !p.isEmpty {
            let std = (p as NSString).standardizingPath
            if let i = items.firstIndex(where: { $0.path == std }) {
                let existing = items.remove(at: i)
                items.insert(existing, at: 0)
                continue
            }
            items.insert(ShelfItem(path: std, addedAt: now, bookmark: bookmark(std)), at: 0)
            added.append(std)
        }
        if items.count > limit { items.removeLast(items.count - limit) }
        return added.reversed()
    }

    public mutating func remove(id: String) { items.removeAll { $0.id == id } }
    public mutating func removeAll() { items.removeAll() }

    /// Drop entries whose file no longer exists.
    public mutating func prune(exists: (String) -> Bool) { items.removeAll { !exists($0.path) } }

    public mutating func updatePath(id: String, to path: String) {
        guard let i = items.firstIndex(where: { $0.id == id }) else { return }
        items[i].path = path
    }
}

// MARK: - System stats

public struct CPUTicks: Equatable, Sendable {
    public var user: UInt64, system: UInt64, idle: UInt64, nice: UInt64
    public init(user: UInt64, system: UInt64, idle: UInt64, nice: UInt64) {
        self.user = user; self.system = system; self.idle = idle; self.nice = nice
    }
}

public struct SystemStats: Equatable, Sendable {
    /// 0...1
    public var cpu: Double
    public var memoryUsed: UInt64
    public var memoryTotal: UInt64

    public init(cpu: Double, memoryUsed: UInt64, memoryTotal: UInt64) {
        self.cpu = cpu; self.memoryUsed = memoryUsed; self.memoryTotal = memoryTotal
    }

    public var memoryFraction: Double { memoryTotal == 0 ? 0 : Double(memoryUsed) / Double(memoryTotal) }

    /// CPU usage between two samples summed over all cores.
    public static func cpuUsage(previous: [CPUTicks], current: [CPUTicks]) -> Double {
        guard previous.count == current.count, !current.isEmpty else { return 0 }
        var busy: UInt64 = 0, total: UInt64 = 0
        for (a, b) in zip(previous, current) {
            let du = b.user &- a.user, ds = b.system &- a.system, dn = b.nice &- a.nice, di = b.idle &- a.idle
            // Counter wrap or reset: skip this core.
            guard b.user >= a.user, b.system >= a.system, b.idle >= a.idle, b.nice >= a.nice else { continue }
            busy += du + ds + dn
            total += du + ds + dn + di
        }
        return total == 0 ? 0 : Double(busy) / Double(total)
    }
}
