import Foundation
import Testing
@testable import IsletCore

/// Clipboard history keeps its privacy promise: every skip rule, and off means empty.
@Suite struct ClipboardTests {
    @Test func switchingOffEmptiesEverythingPinnedToo() {
        var h = ClipboardHistory()
        h.add("keep me", types: [], sourceBundleID: nil, now: t0)
        h.add("and me", types: [], sourceBundleID: nil, now: t0)
        h.togglePin(id: h.entries[0].id)
        h.clear()
        // "Clear unpinned" leaves the pinned one...
        #expect(h.entries.map(\.text) == ["and me"])
        #expect(!h.hasUnpinned)
        // ...switching off leaves nothing.
        h.removeAll()
        #expect(h.entries.isEmpty)
    }

    @Test(arguments: ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
                      "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType"])
    func concealedTransientAndGeneratedTypesAreSkipped(type: String) {
        var h = ClipboardHistory()
        #expect(h.add("hunter2", types: ["public.utf8-plain-text", type], sourceBundleID: "com.apple.TextEdit", now: t0) == .ignored)
        #expect(h.entries.isEmpty)
    }

    @Test func passwordManagersAreAlwaysSkipped() {
        #expect(ClipboardHistory.ignoredApps.count == 9)
        for app in ClipboardHistory.ignoredApps {
            var h = ClipboardHistory()
            h.skipsSecrets = false
            #expect(h.add("plain words", types: [], sourceBundleID: app, now: t0) == .ignored, "\(app)")
        }
    }

    @Test func appsTheUserIgnoredAreSkippedAndForgotten() {
        var h = ClipboardHistory()
        h.add("from notes", types: [], sourceBundleID: "com.apple.Notes", now: t0)
        h.add("from mail", types: [], sourceBundleID: "com.apple.mail", now: t0)
        h.togglePin(id: h.entries.first { $0.text == "from notes" }!.id)
        h.ignoredApps = ["com.apple.Notes"]
        // What was kept from it goes, pinned or not.
        #expect(h.entries.map(\.text) == ["from mail"])
        #expect(h.add("again", types: [], sourceBundleID: "com.apple.Notes", now: t0) == .ignored)
        #expect(h.add("still fine", types: [], sourceBundleID: "com.apple.mail", now: t0) == .added)
    }

    @Test func likelyPasswordsFromABrowserAreSkipped() {
        var h = ClipboardHistory()
        #expect(h.add("fujvy7-Bezkah-doqnij", types: [], sourceBundleID: "com.apple.Safari", now: t0) == .ignored)
        #expect(h.add("xT3!kP9#qr", types: [], sourceBundleID: "com.google.Chrome", now: t0) == .ignored)
        // The same text from another app is kept: only browsers copy for password extensions.
        #expect(h.add("fujvy7-Bezkah-doqnij", types: [], sourceBundleID: "com.apple.Terminal", now: t0) == .added)
        // A link, a sentence and a short word from a browser are kept.
        #expect(h.add("https://example.com/Path?q=1", types: [], sourceBundleID: "com.apple.Safari", now: t0) == .added)
        #expect(h.add("Meet at 5 PM!", types: [], sourceBundleID: "com.apple.Safari", now: t0) == .added)
        // Switched off, it keeps them.
        h.skipsSecrets = false
        #expect(h.add("xT3!kP9#qr", types: [], sourceBundleID: "com.google.Chrome", now: t0) == .added)
    }

    @Test(arguments: [
        ("fujvy7-Bezkah-doqnij", true),
        ("xT3!kP9#qr", true),
        ("Abcdefg1", true),
        ("Ab1!", false),                         // too short
        ("abcdefgh", false),                     // one kind of character
        ("abcd1234", false),                     // two kinds
        ("correct horse Battery 9", false),      // has spaces
        ("https://github.com/Owner/Repo1", false),
        ("www.Example.com/A1", false),
        ("/Users/Me/Doc-1.txt", false),
        ("~/Code/App-2", false),
        ("Jane.Doe1@example.com", false),
        ("github.com/Owner-1/Repo", false),
        (String(repeating: "aA1-", count: 33), false), // over 128
    ])
    func whatLooksLikeASecret(text: String, secret: Bool) {
        #expect(ClipboardHistory.looksLikeSecret(text) == secret, "\(text)")
    }

    @Test func blankAndHugeTextIsSkipped() {
        var h = ClipboardHistory()
        #expect(h.add("   \n", types: [], sourceBundleID: nil, now: t0) == .ignored)
        #expect(h.add(String(repeating: "a", count: ClipboardHistory.maxTextLength + 1), types: [], sourceBundleID: nil, now: t0) == .ignored)
        #expect(h.add(String(repeating: "a", count: ClipboardHistory.maxTextLength), types: [], sourceBundleID: nil, now: t0) == .added)
    }

    @Test func aDuplicateMovesToTheTop() {
        var h = ClipboardHistory()
        h.add("one", types: [], sourceBundleID: "com.apple.Notes", now: t0)
        h.add("two", types: [], sourceBundleID: nil, now: t0.addingTimeInterval(1))
        #expect(h.add("one", types: [], sourceBundleID: nil, now: t0.addingTimeInterval(2)) == .moved)
        #expect(h.entries.map(\.text) == ["one", "two"])
        #expect(h.entries[0].date == t0.addingTimeInterval(2))
        // The app it came from is kept when the copy doesn't say.
        #expect(h.entries[0].sourceBundleID == "com.apple.Notes")
    }

    @Test func settingsCarryTheRules() {
        let s = IsletSettings.decodeLenient(Data(#"{"clipboardIgnoredApps": [" com.apple.Notes", "com.apple.Notes", ""], "clipboardSkipSecrets": false}"#.utf8))
        #expect(s.clipboardIgnoredApps == ["com.apple.Notes"])
        #expect(!s.clipboardSkipSecrets)
        #expect(IsletSettings().clipboardSkipSecrets)
        #expect(IsletSettings().clipboardIgnoredApps.isEmpty)
    }
}

@Suite struct CalmIslandTests {
    @Test func welcomeBackOnlyWhenSomethingArrived() {
        let name: (String) -> String = { $0 == "com.apple.mail" ? "Mail" : $0 }
        #expect(WelcomeBack.activity(counts: [:], lockedFor: 3600, name: name) == nil)
        #expect(WelcomeBack.activity(counts: ["ci": 0], lockedFor: 3600, name: name) == nil)
        // A short lock says nothing either.
        #expect(WelcomeBack.activity(counts: ["ci": 2], lockedFor: 30, name: name) == nil)
        let one = WelcomeBack.activity(counts: ["com.apple.mail": 3], lockedFor: 120, name: name)
        #expect(one?.subtitle == "3 from Mail")
        #expect(one?.id == "welcome-back")
        let many = WelcomeBack.activity(counts: ["b": 2, "a": 2, "c": 5, "d": 1], lockedFor: 120, name: name)
        #expect(many?.subtitle == "5 from c · 2 from a · 2 from b")
    }

    @Test func clipboardIsListedOnlyWhileItIsOn() {
        var s = IsletSettings()
        s.clipboardEnabled = false
        #expect(!IslandPage.switcher(s, current: .home).more.contains(.clipboard))
        // Opened some other way, it still shows where you are.
        #expect(IslandPage.switcher(s, current: .clipboard).more == IslandPage.switcher(s, current: nil).more + [.clipboard])
        s.clipboardEnabled = true
        #expect(IslandPage.switcher(s, current: .home).more.first == .clipboard)
    }

    @Test func pagesFollowTheirSwitches() {
        var s = IsletSettings()
        s.calendarEnabled = false; s.remindersEnabled = false; s.shelfEnabled = false
        s.pluginsEnabled = false; s.systemStatsEnabled = false; s.clipboardEnabled = false
        let bare = IslandPage.switcher(s, current: .home)
        #expect(bare.main == [.home] && bare.more.isEmpty)
        s.remindersEnabled = true; s.shelfEnabled = true; s.pluginsEnabled = true; s.systemStatsEnabled = true
        let full = IslandPage.switcher(s, current: .home)
        #expect(full.main == [.home, .today, .shelf])
        #expect(full.more == [.widgets, .stats])
    }
}
