#!/usr/bin/env python3
"""Generate Sources/IsletCore/LiveActivityApps.swift from the Live Activity catalogue.

The research catalogue (docs/research/07-live-activity-apps.json) lists the apps with
evidence of a Live Activity. EXTRAS below adds names Islet already recognised before that
catalogue existed (parcel carriers, regional apps, system activities under their own name).
The research entries win: an extra may not reuse an app name from the JSON.

Usage:
  scripts/gen-live-activity-apps.py           write the Swift file
  scripts/gen-live-activity-apps.py --check   exit 1 if the Swift file is out of date
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs/research/07-live-activity-apps.json"
OUTPUT = ROOT / "Sources/IsletCore/LiveActivityApps.swift"

TEMPLATES = {
    "eta": "eta", "stages": "stages", "flight": "flight", "route": "route", "score": "score",
    "timer": "timer", "workout": "workout", "gauge": "gauge", "live-audio": "liveAudio",
    "media": "media", "agent": "agent", "progress": "progress",
}
CATEGORIES = {
    "system", "rideshare", "ev-parking", "delivery", "travel", "transit", "sports", "fitness", "health",
    "productivity", "cooking", "weather", "finance", "ai", "developer", "home", "media",
}

EXTRAS = [
    {"app": "Stopwatch", "category": "system", "symbol": "stopwatch.fill", "tint": "#FF9F0A", "template": "timer"},
    {"app": "Alarm", "category": "system", "symbol": "alarm.fill", "tint": "#FF9F0A", "template": "timer"},
    {"app": "Find My", "category": "system", "symbol": "location.fill", "tint": "#30D158", "template": "progress"},
    {"app": "Ola", "category": "rideshare", "symbol": "car.fill", "tint": "#CDDC39", "template": "eta"},
    {"app": "Deliveroo", "category": "delivery", "symbol": "takeoutbag.and.cup.and.straw.fill", "tint": "#00CCBC", "template": "eta"},
    {"app": "Blinkit", "category": "delivery", "symbol": "cart.fill", "tint": "#F8CB46", "template": "eta"},
    {"app": "Amazon", "category": "delivery", "symbol": "shippingbox.fill", "tint": "#FF9900", "template": "stages"},
    {"app": "Parcel", "category": "delivery", "symbol": "shippingbox.fill", "tint": "#AC8E68", "template": "stages"},
    {"app": "FedEx", "category": "delivery", "symbol": "shippingbox.fill", "tint": "#4D148C", "template": "stages"},
    {"app": "UPS", "category": "delivery", "symbol": "shippingbox.fill", "tint": "#FFB500", "template": "stages"},
    {"app": "DHL", "category": "delivery", "symbol": "shippingbox.fill", "tint": "#FFCC00", "template": "stages"},
    {"app": "IndiGo", "category": "travel", "symbol": "airplane", "tint": "#1A2B6D", "template": "flight"},
    {"app": "Air India", "category": "travel", "symbol": "airplane", "tint": "#DA0E29", "template": "flight"},
    {"app": "Cricbuzz", "category": "sports", "symbol": "figure.cricket", "tint": "#1AA355", "template": "score"},
    {"app": "OneFootball", "category": "sports", "symbol": "soccerball", "tint": "#FFFFFF", "template": "score"},
    {"app": "Spotify", "category": "media", "symbol": "music.note", "tint": "#1ED760", "template": "media"},
    {"app": "YouTube Music", "category": "media", "symbol": "music.note", "tint": "#FF0000", "template": "media"},
    {"app": "Claude", "category": "ai", "symbol": "sparkle", "tint": "#D97757", "template": "agent"},
]


def fail(message):
    sys.exit(f"gen-live-activity-apps: {message}")


def validate(entries, label):
    for e in entries:
        name = e.get("app") or fail(f"{label}: entry without an app name")
        if e["template"] not in TEMPLATES:
            fail(f"{name}: unknown template {e['template']!r}")
        if e["category"] not in CATEGORIES:
            fail(f"{name}: unknown category {e['category']!r}")
        if not re.fullmatch(r"#[0-9A-Fa-f]{6}", e["tint"]):
            fail(f"{name}: tint {e['tint']!r} is not #RRGGBB")
        if not re.fullmatch(r"[a-z0-9.]+", e["symbol"]):
            fail(f"{name}: odd symbol name {e['symbol']!r}")


def swift_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(entries):
    lines = [
        "// Generated by scripts/gen-live-activity-apps.py from docs/research/07-live-activity-apps.json.",
        "// Do not edit by hand: change the JSON or the script's extras, then run the script.",
        "",
        "extension LiveActivityCatalog {",
        f"    /// {len(entries)} apps: the research catalogue first, then Islet's own additions.",
        "    static let apps: [Look] = [",
    ]
    for e in entries:
        bundle = swift_string(e["bundleID"]) if e.get("bundleID") else "nil"
        aliases = "[" + ", ".join(swift_string(a) for a in e.get("aliases", [])) + "]"
        lines.append(
            f"        Look(app: {swift_string(e['app'])}, bundleID: {bundle}, aliases: {aliases}, "
            f"category: {swift_string(e['category'])}, symbol: {swift_string(e['symbol'])}, "
            f"tint: {swift_string(e['tint'].upper())}, template: .{TEMPLATES[e['template']]}),"
        )
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main():
    research = json.loads(SOURCE.read_text())
    validate(research, "research")
    validate(EXTRAS, "extras")
    names = [e["app"].lower() for e in research]
    if len(names) != len(set(names)):
        fail("duplicate app names in the research JSON")
    for e in EXTRAS:
        if e["app"].lower() in names:
            fail(f"extra {e['app']!r} duplicates a research entry")
    text = render(research + EXTRAS)
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            fail(f"{OUTPUT.relative_to(ROOT)} is out of date; run scripts/gen-live-activity-apps.py")
        return
    OUTPUT.write_text(text)
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(research)} research entries, {len(EXTRAS)} extras)")


if __name__ == "__main__":
    main()
